//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetIdentity.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_Answers
    {
        public int Id_Answer { get; set; }
        public Nullable<int> Id_Question { get; set; }
        public string Answer { get; set; }
        public Nullable<bool> Has_Weight { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<bool> Has_CorrectAnswer { get; set; }
        public Nullable<bool> CorrectAnswer { get; set; }
    }
}
