//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetIdentity.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_Dimension_Notes
    {
        public int Id { get; set; }
        public int Id_Dimension { get; set; }
        public int W_Min { get; set; }
        public int W_Max { get; set; }
        public int Score { get; set; }
        public string Note { get; set; }
    }
}
