//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetIdentity.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_Factors
    {
        public int Id_Factor { get; set; }
        public int Id_Dimension { get; set; }
        public string Factor { get; set; }
        public bool Has_Weight { get; set; }
        public Nullable<int> Weight { get; set; }
        public bool Has_Time { get; set; }
        public Nullable<int> Time { get; set; }
    }
}
