//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetIdentity.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_Tests
    {
        public int Id_Test { get; set; }
        public int Id_Account { get; set; }
        public int Id_User { get; set; }
        public string Test { get; set; }
        public string Description { get; set; }
        public string Version { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<int> ApplicationTime { get; set; }
        public string ImageName { get; set; }
    }
}
