//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetIdentity.WebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AspNetIdentityEntities : DbContext
    {
        public AspNetIdentityEntities()
            : base("name=AspNetIdentityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accounts> Accounts { get; set; }
        public virtual DbSet<Accounts_AdditionalInformation> Accounts_AdditionalInformation { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<CT_Tests> CT_Tests { get; set; }
        public virtual DbSet<CT_Answers> CT_Answers { get; set; }
        public virtual DbSet<CT_Dimensions> CT_Dimensions { get; set; }
        public virtual DbSet<CT_Factors> CT_Factors { get; set; }
        public virtual DbSet<CT_Questions> CT_Questions { get; set; }
        public virtual DbSet<Temp_AspNetUsersTests> Temp_AspNetUsersTests { get; set; }
        public virtual DbSet<Temp_AspNetUsersTests_Details> Temp_AspNetUsersTests_Details { get; set; }
        public virtual DbSet<PERFIL> PERFIL { get; set; }
        public virtual DbSet<PERFIL_COMPETENCIAS> PERFIL_COMPETENCIAS { get; set; }
        public virtual DbSet<PERFIL_CONOCIMIENTOS> PERFIL_CONOCIMIENTOS { get; set; }
        public virtual DbSet<PERFIL_CT_AREA> PERFIL_CT_AREA { get; set; }
        public virtual DbSet<PERFIL_CT_COMPETENCIAS> PERFIL_CT_COMPETENCIAS { get; set; }
        public virtual DbSet<PERFIL_CT_ESCOLARIDAD> PERFIL_CT_ESCOLARIDAD { get; set; }
        public virtual DbSet<PERFIL_CT_ESPECIALIDAD> PERFIL_CT_ESPECIALIDAD { get; set; }
        public virtual DbSet<PERFIL_CT_IDIOM_NIVEL> PERFIL_CT_IDIOM_NIVEL { get; set; }
        public virtual DbSet<PERFIL_CT_IDIOMAS> PERFIL_CT_IDIOMAS { get; set; }
        public virtual DbSet<PERFIL_CT_SUB_AREA> PERFIL_CT_SUB_AREA { get; set; }
        public virtual DbSet<PERFIL_CT_TIPOS_COMPETENCIAS> PERFIL_CT_TIPOS_COMPETENCIAS { get; set; }
        public virtual DbSet<PERFIL_FINALIDADES> PERFIL_FINALIDADES { get; set; }
        public virtual DbSet<PERFIL_FORMA_IDIOMAS> PERFIL_FORMA_IDIOMAS { get; set; }
        public virtual DbSet<PERFIL_FORMACION> PERFIL_FORMACION { get; set; }
        public virtual DbSet<PERFIL_PROCESOS> PERFIL_PROCESOS { get; set; }
        public virtual DbSet<PERFIL_RELACIONES> PERFIL_RELACIONES { get; set; }
        public virtual DbSet<HV_ACTITUDES> HV_ACTITUDES { get; set; }
        public virtual DbSet<HV_CONOCIMIENTOS> HV_CONOCIMIENTOS { get; set; }
        public virtual DbSet<HV_CT_ACTITUDES> HV_CT_ACTITUDES { get; set; }
        public virtual DbSet<HV_CT_CARGO> HV_CT_CARGO { get; set; }
        public virtual DbSet<HV_CT_CIUDAD> HV_CT_CIUDAD { get; set; }
        public virtual DbSet<HV_CT_CONOCIMIENTOS> HV_CT_CONOCIMIENTOS { get; set; }
        public virtual DbSet<HV_CT_DEPTO> HV_CT_DEPTO { get; set; }
        public virtual DbSet<HV_CT_DISIPLINA> HV_CT_DISIPLINA { get; set; }
        public virtual DbSet<HV_CT_EMPRESAS> HV_CT_EMPRESAS { get; set; }
        public virtual DbSet<HV_CT_ESTADO_CIVIL> HV_CT_ESTADO_CIVIL { get; set; }
        public virtual DbSet<HV_CT_INSTITUCION> HV_CT_INSTITUCION { get; set; }
        public virtual DbSet<HV_CT_PAIS> HV_CT_PAIS { get; set; }
        public virtual DbSet<HV_CT_TIPO_IDENTIFICACION> HV_CT_TIPO_IDENTIFICACION { get; set; }
        public virtual DbSet<HV_CT_TITULOS> HV_CT_TITULOS { get; set; }
        public virtual DbSet<HV_DATOS_BASICOS> HV_DATOS_BASICOS { get; set; }
        public virtual DbSet<HV_ESTUDIOS> HV_ESTUDIOS { get; set; }
        public virtual DbSet<HV_EXPERIENCIA> HV_EXPERIENCIA { get; set; }
        public virtual DbSet<HV_UBICACION> HV_UBICACION { get; set; }
        public virtual DbSet<HV_CT_GENERO> HV_CT_GENERO { get; set; }
        public virtual DbSet<Cat_StatusTest> Cat_StatusTest { get; set; }
        public virtual DbSet<CT_Dimension_Notes> CT_Dimension_Notes { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
    }
}
