//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetIdentity.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HV_CT_TITULOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HV_CT_TITULOS()
        {
            this.HV_ESTUDIOS = new HashSet<HV_ESTUDIOS>();
        }
    
        public int ID_CT_TITULOS { get; set; }
        public int ID_CT_PAIS { get; set; }
        public int ID_CT_DEPTO { get; set; }
        public int ID_CT_CIUDAD { get; set; }
        public string NOMBRE { get; set; }
        public int TIPO { get; set; }
        public Nullable<int> ESTADO { get; set; }
    
        public virtual HV_CT_PAIS HV_CT_PAIS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HV_ESTUDIOS> HV_ESTUDIOS { get; set; }
    }
}
