//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetIdentity.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HV_DATOS_BASICOS
    {
        public int ID_DATOS_BASICOS { get; set; }
        public int ID_CT_PAIS { get; set; }
        public int ID_CT_DEPTO { get; set; }
        public int ID_CT_CIUDAD { get; set; }
        public int ID_CT_ESTADO_CIVIL { get; set; }
        public int ID_CT_TIPO_IDENTIFICACION { get; set; }
        public string NOMBRES { get; set; }
        public string APELLIDOS { get; set; }
        public int IDENTIFICACION { get; set; }
        public System.DateTime F_NACIMIENTO { get; set; }
        public int GENERO { get; set; }
        public string DIRECCION { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> ESTADO { get; set; }
        public Nullable<int> ID_USERS { get; set; }
        public Nullable<int> ID_PERFIL { get; set; }
    }
}
