//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetIdentity.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HV_EXPERIENCIA
    {
        public int ID_EXPERIENCIA { get; set; }
        public int ID_DATOS_BASICOS { get; set; }
        public int ID_CT_EMPRESA { get; set; }
        public int ID_CT_CARGO { get; set; }
        public System.DateTime DESDE { get; set; }
        public System.DateTime HASTA { get; set; }
        public int TRABAJO_ACTUAL { get; set; }
        public string DESCRIPCION { get; set; }
        public string ARCHIVO_RUTA { get; set; }
        public Nullable<int> ESTADO { get; set; }
    
        public virtual HV_CT_CARGO HV_CT_CARGO { get; set; }
        public virtual HV_CT_EMPRESAS HV_CT_EMPRESAS { get; set; }
    }
}
