//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetIdentity.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HV_ESTUDIOS
    {
        public int ID_ESTUDIOS { get; set; }
        public int ID_DATOS_BASICOS { get; set; }
        public int ID_CT_INSTITUCION { get; set; }
        public int ID_CT_TITULOS { get; set; }
        public int ID_CT_DISIPLINA { get; set; }
        public System.DateTime DESDE { get; set; }
        public System.DateTime HASTA { get; set; }
        public int NOTA { get; set; }
        public string DESCRIPCION { get; set; }
        public string ARCHIVO_RUTA { get; set; }
        public string ACTIVIDADES { get; set; }
        public Nullable<int> ESTADO { get; set; }
    
        public virtual HV_CT_DISIPLINA HV_CT_DISIPLINA { get; set; }
        public virtual HV_CT_INSTITUCION HV_CT_INSTITUCION { get; set; }
        public virtual HV_CT_TITULOS HV_CT_TITULOS { get; set; }
    }
}
