//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetIdentity.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HV_UBICACION
    {
        public int ID_DATOS_BASICOS { get; set; }
        public Nullable<int> ID_CT_PAIS { get; set; }
        public Nullable<int> ID_CT_DEPTO { get; set; }
        public Nullable<int> ID_CT_CIUDAD { get; set; }
        public int ID_HV_HUBICACION { get; set; }
        public string NOMENCLATURA { get; set; }
        public string LOCALIDAD { get; set; }
        public Nullable<int> ESTADO { get; set; }
    }
}
