//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetIdentity.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERFIL_CT_COMPETENCIAS
    {
        public int ID_CT_COMPETENCIA { get; set; }
        public int ID_TIPO_COMPET { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public int ESTADO { get; set; }
    
        public virtual PERFIL_CT_TIPOS_COMPETENCIAS PERFIL_CT_TIPOS_COMPETENCIAS { get; set; }
    }
}
