//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetIdentity.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERFIL_FINALIDADES
    {
        public int ID_FINALIDAD { get; set; }
        public int ID_PERFIL { get; set; }
        public string ACCION { get; set; }
        public string FUNCION { get; set; }
        public string RESULTADOS { get; set; }
        public Nullable<int> ESTADO { get; set; }
    
        public virtual PERFIL PERFIL { get; set; }
    }
}
