//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetIdentity.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERFIL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERFIL()
        {
            this.PERFIL_COMPETENCIAS = new HashSet<PERFIL_COMPETENCIAS>();
            this.PERFIL_CONOCIMIENTOS = new HashSet<PERFIL_CONOCIMIENTOS>();
            this.PERFIL_FINALIDADES = new HashSet<PERFIL_FINALIDADES>();
            this.PERFIL_PROCESOS = new HashSet<PERFIL_PROCESOS>();
            this.PERFIL_RELACIONES = new HashSet<PERFIL_RELACIONES>();
        }
    
        public int ID_PERFIL { get; set; }
        public int ID_CT_AREA { get; set; }
        public int ID_CT_SUB_AREA { get; set; }
        public string NOMBRE { get; set; }
        public int REPORTA { get; set; }
        public int SUPERVISA { get; set; }
        public string OBJETIVO { get; set; }
        public Nullable<int> ESTADO { get; set; }
        public Nullable<int> ID_ACCOUNTS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERFIL_COMPETENCIAS> PERFIL_COMPETENCIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERFIL_CONOCIMIENTOS> PERFIL_CONOCIMIENTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERFIL_FINALIDADES> PERFIL_FINALIDADES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERFIL_PROCESOS> PERFIL_PROCESOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERFIL_RELACIONES> PERFIL_RELACIONES { get; set; }
    }
}
